config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  get 'users/new'
  get 'users/index'
  get 'users/:id' => "users#show",as: "user_show"
  get 'users/:id/edit' => "users#edit",as: "user_edit"
  patch "users/:id" => "users#update",as: "user_update"
  get 'books/new'
  get 'books/index'
  get 'books/:id' => "books#show",as: "book_show"
  get 'books/:id/edit' => "books#edit",as: "book_edit"
  patch "books/:id" => "books#update",as: "book_update"
  post "books" => "books#create"
  delete "books/:id" => "books#destroy",as: "book_destroy"
  get 'homes/top'
  get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  has_one_attached :image
  
  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      image.attach(io: File.open(file_path),filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [width,height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_show_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_show_path(@book.id)
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.new
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_show_path(@book.id)
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_index_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:show]
  
  def new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @user_books = @user.books.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_show_path(@user.id)
  end
  
  private
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to root_path
    end
  end
  
  def user_params
    params.require(:user).permit(:name,:image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-ml 10 col-xl-8 d-flex justify-content-center">
      <div class="user_info w-50 mt-4">
        <h2>Editing Book</h2>
        <%= form_with model: @book,url: book_update_path(@book.id), method: :patch do |f| %>
          <p>Title</p>
          <%= f.text_field :title,class: "form-control mb-3" %>
          <p>Opinion</p>
          <%= f.text_area :body,class: "form-control mb-3" %>
          <%= f.submit "Update Book",class: "btn btn-success text-white mb-3" %>
        <% end %>
        <p>
          <%= link_to "Show",book_show_path(@book.id) %> | <%= link_to "Back",books_index_path %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 mx-auto">
      <div class="row">
        <div class="col-4">
          <%= render "users/common", user: @user, book: @book %>
        </div>
        <div class="col-8">
          <div class="users">
            <h2 class="mt-4">Books</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th colspan="2">Opinion</th>
                </tr>
              </thead>
              <% @books.each do |book| %>
              <tbody>
                <tr>
                  <td><%= image_tag book.user.get_image(80,80) %></td>
                  <td>
                    <%= link_to book_show_path(book.id) do %>
                      <%= book.title %>
                    <% end %>
                  </td>
                  <td colspan="2"><%= book.body %></td>
                </tr>
              </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 mx-auto">
      <div class="row">
        <div class="col-4">
          <%= render "users/common", user: @user, book: @book %>
        </div>
        <div class="col-8">
          <div class="users">
            <h2 class="mt-4">Book detail</h2>
            <table class="table">
              <tr>
                <td>
                  <%= image_tag @user.get_image(80,80) %><br>
                  <%= link_to user_show_path(@user.id) do %>
                    <%= @user.name %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_show_path(@book_detail.id) do %>
                    <%= @book_detail.title %>
                  <% end %>
                </td>
                <td><%= @book_detail.body %></td>
                <% if @user == current_user %>
                  <td>
                    <%= link_to book_edit_path(@book_detail.id),class: "btn btn-success btn-sm" do %>
                      <span>Edit</span>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to book_destroy_path(@book_detail.id),method: :delete,"data-confirm" => "本当に削除しますか？",class: "btn btn-danger btn-sm" do %>
                      <span>Destroy</span>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-sm-10 col-md-9 col-lg-7 mx-auto">
      <div class="title mt-3 text-center">
        <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
      </div>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 col-sm-10 col-md-9 col-lg-7 mx-auto">
      <div class="title mt-3">
        <h1>welcome to <i class="fas fa-book"></i>Bookers!!</h1>
      </div>
      <div class="text">
        <p class="my-2">In <i class="fas fa-book"></i><span class="font-weight-bold">Bookers</span>,</p>
        <p class="my-2">you can share and exchange your opinions, inpressions, and emotions</p>
        <p class="my-2">about various books!</p>
        </p>
      </div>
      <%= link_to new_user_session_path do %>
        <div class="row w-100">
          <div class="col-10 mx-auto btn btn-info">Log in</div>
        </div>
      <% end %>
      <%= link_to new_user_registration_path do %>
        <div class="row w-100">
          <div class="col-10 mx-auto btn btn-success mt-3">Sign up</div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/09cda450ea.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="d-flex justify-content-around h-100 bg-dark">
      <div class="title">
        <a href="/" class="text-decoration-none"><h4 class="text-white p-3 mb-0">Bookers</h4></a>
      </div>
      <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item mr-3">
                <%= link_to user_show_path(current_user.id),class: "text-white text-decoration-none" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to users_index_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to books_index_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to destroy_user_session_path,method: :delete,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li class="nav-item mr-3">
                <%= link_to root_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to homes_about_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to new_user_registration_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item mr-3">
                <%= link_to new_user_session_path,class: "text-white text-decoration-none" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <div class="footer mt-5 w-100 mx-auto">
      <p class="text-center">CopyRight Infratop.inc</p>
    </div>
  </body>
</html>

app/views/users/_common.html.erb
<div class="user_info">
  <h2 class="mt-4">User info</h2>
  <%= image_tag user.get_image(150,150) %><br>
  <table class="table table-top-bordered">
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </table>
  <%= link_to user_edit_path(user.id),class: "btn btn-outline-secondary w-100" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<div class="new_book">
  <h2 class="mt-4">New book</h2>
  <%= form_with model: book,url: books_path,method: :post do |f| %>
    <p>Title</p>
    <%= f.text_field :title %>
    <p class="mt-2">Opinion</p>
    <%= f.text_area :body %>
    
    <%= f.submit "Create Book",class: "btn btn-success mt-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-ml 10 col-xl-8 d-flex justify-content-center">
      <div class="user_info w-50 mt-4">
        <h2>User info</h2>
        <%= form_with model: @user,url: user_update_path(@user.id), method: :patch do |f| %>
          <p>name</p>
          <%= f.text_field :name,class: "form-control mb-3" %>
          <p>image</p>
          <%= f.file_field :image,class: "mb-3" %>
          <p>introduction</p>
          <%= f.text_area :introduction,class: "form-control mb-3" %>
          <%= f.submit "Update User",class: "btn btn-secondary text-white" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 mx-auto">
      <div class="row">
        <div class="col-4">
          <%= render "common", user: @user, book: @book %>
        </div>
        <div class="col-8">
          <div class="users">
            <h2 class="mt-4">Users</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>images</th>
                  <th>name</th>
                  <th></th>
                </tr>
              </thead>
              <% @users.each do |user| %>
              <tbody>
                <tr>
                  <td><%= image_tag user.get_image(80,80) %></td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= link_to user_show_path(user.id) do %>
                      <p>Show</p>
                    <% end %>
                  </td>
                </tr>
              </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 mx-auto">
      <div class="row">
        <div class="col-4">
          <%= render "common", user: @user, book: @book %>
        </div>
        <div class="col-8">
          <div class="users">
            <h2 class="mt-4">Books</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th></th>
                  <th>Title</th>
                  <th colspan="2">Opinion</th>
                </tr>
              </thead>
              <% @user_books.each do |user_book| %>
              <tbody>
                <tr>
                  <td><%= image_tag @user.get_image(80,80) %></td>
                  <td>
                    <%= link_to book_show_path(user_book.id) do %>
                      <%= user_book.title %>
                    <% end %>
                  </td>
                  <td colspan="2"><%= user_book.body %></td>
                </tr>
              </tbody>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>